@echo off
setlocal enabledelayedexpansion

:: Initialisation
echo :: This file was automatically generated by titanium.>%2
echo.>>%2
echo @echo off>>%2

:: Read the files the program needs line by line
set count=0
for /f "delims=*" %%y in (%1) do (
   set /a count+=1
   set lines[!count!]=%%y
)

:: Split each line into 2 sections:
::    The command e.g. "glider"
::    The value e.g. "'Hello world'"
:: And then compile to batch.
for /L %%z in (1, 1, %count%) do (
   :: Run through every line
   for /F "delims=: tokens=1,2,3,4" %%a in ("!lines[%%z]!") do (
      :: Check if %%a is a keyword
      if %%a == glider (
         echo echo [93m%%b[0m>>%2
      ) else if %%a == block (
         echo set /p v=[96m%%b[0m>>%2
      ) else if %%a == blinker (
         echo echo [91m%%b[0m>>%2
         echo exit /b>>%2
      ) else if %%a == eater (
         echo exit /b>>%2 
      ) else if %%a == gun (
         if %%c == glider (
            echo for /L %%%%s in %%b do echo [93m%%d[0m>>%2
         ) else if %%c == block (
            echo for /L %%%%s in %%b do set /p v=[96m%%d[0m>>%2
         )
      )
   )
)